apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev
resources:
- ../base

images:
- name: nginx
  newName: nginx
  newTag: "1.20"

patches:
- path: replicas.yaml

commonLabels:
  environment: development
  app: calci

configMapGenerator:
- name: sample-configmap
  literals:
  - CRED=7298479
  - APP_PORT=8080
