apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "google.com"
    http:
      paths:
      - pathType: Prefix
        path: "/path"
        backend:
          service:
            name: calci
            port:
              number: 80
